name: ContinuousIntegration Release NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/sverigesradio/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create NuGet Package
      run: dotnet pack -c PackNuGet /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/sverigesradio/nuget-ember-plus-consumer-lib/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ./src/

    - name: Upload NuGet Package
      uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1.0.0
      with:
        name: SR.EmberPlusConsumerLib.NetStandard
        path: ./src/Nuget.EmberPlusConsumerLib.NetStandard/bin/PackNuGet/SR.EmberPlusConsumerLib.NetStandard.${{ github.event.release.tag_name }}.nupkg

    - name: Publish NuGet Package
      run: dotnet nuget push ./src/Nuget.EmberPlusConsumerLib.NetStandard/bin/PackNuGet/SR.EmberPlusConsumerLib.NetStandard.${{ github.event.release.tag_name }}.nupkg --skip-duplicate --no-symbols true -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/sverigesradio/index.json
